# Generated by Django 4.2.3 on 2023-09-28 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='/imageholder.png', null=True, upload_to=''),
        ),
    ]
